#pragma once

#include <string>
#include <config.h>  // Generated by CMake from config.h.in

namespace smpp {

/**
 * @class AppInfo
 * @brief Application information and version details
 *
 * Provides access to version and build information.
 * All values come from CMake configuration (config.h).
 */
class AppInfo {
public:
    /**
     * Get application name
     * @return Project name
     */
    static constexpr const char* name() {
        return PROJECT_NAME;
    }

    /**
     * Get version string (e.g., "0.1.0")
     * @return Full version string
     */
    static constexpr const char* version() {
        return VERSION_STRING;
    }

    /**
     * Get full version with status (e.g., "0.1.0 - pre-release")
     * @return Full version with status
     */
    static constexpr const char* full_version() {
        return FULL_VERSION_STRING;
    }

    /**
     * Get version components
     */
    static constexpr int version_major() { return VERSION_MAJOR; }
    static constexpr int version_minor() { return VERSION_MINOR; }
    static constexpr int version_patch() { return VERSION_PATCH; }

    /**
     * Get description
     * @return Project description
     */
    static constexpr const char* description() {
        return PROJECT_DESCRIPTION;
    }

    /**
     * Get homepage URL
     * @return Project homepage
     */
    static constexpr const char* homepage() {
        return PROJECT_HOMEPAGE_URL;
    }

    /**
     * Get build information
     */
    static constexpr const char* compiler() { return COMPILER; }
    static constexpr const char* cxx_standard() { return CXX_STANDARD; }
    static constexpr const char* build_type() { return BUILD_TYPE; }

    /**
     * Check if this is a pre-release version
     * @return true if major version is 0
     */
    static constexpr bool is_prerelease() {
        return VERSION_MAJOR == 0;
    }

    /**
     * Check if this is stable version (1.0.0+)
     * @return true if major version is >= 1
     */
    static constexpr bool is_stable() {
        return VERSION_MAJOR >= 1;
    }

    /**
     * Get human-readable info string
     * @return Formatted info string
     */
    static std::string info_string();

    /**
     * Print info to stdout
     */
    static void print_info();
};

}  // namespace smpp
