#pragma once

/**
 * @file config.h
 * @brief Auto-generated configuration file from CMake
 *
 * This file is generated during build time from config.h.in
 * DO NOT edit this file directly - modify CMakeLists.txt instead
 */

/* Project Information */
#define PROJECT_NAME "simple_smpp_server"
#define PROJECT_VERSION "0.1.0"
#define PROJECT_DESCRIPTION "SMPP Server - Process-per-client microservices"
#define PROJECT_HOMEPAGE_URL "https://github.com/rajesh6115/opensmsc"

/* Version Components */
#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_PATCH 0

/* Version Status */
#define VERSION_STATUS "pre-release (architecture design)"

/* Build Information */
#define BUILD_DATE ""
#define BUILD_TYPE ""
#define COMPILER "GNU 13.3.0"
#define CXX_STANDARD "17"

/* Feature Flags */
#define ENABLE_DBUS 1
#define ENABLE_SPDLOG 1
#define ENABLE_ASIO 1

/* String Helpers */
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define VERSION_STRING \
    TOSTRING(VERSION_MAJOR) "." \
    TOSTRING(VERSION_MINOR) "." \
    TOSTRING(VERSION_PATCH)

#define FULL_VERSION_STRING \
    VERSION_STRING " - " VERSION_STATUS

#endif /* CONFIG_H */
